####################################################################################
#                                                                                  #
#                                                                                  #
#                                AUTOMATIONS                                       #
#                                                                                  #
#                                                                                  #
####################################################################################

- alias: 'Allumer les lumières au couché du soleil'
  initial_state: 'on'
  trigger:
    platform: sun
    event: sunset
    offset: -01:30:00
  action:
    service: homeassistant.turn_on
    entity_id: group.lumieres_salon

####################################################################################
#                                                                                  #
#                                                                                  #
#                                PLEX & CAST                                       #
#                                                                                  #
#                                                                                  #
####################################################################################

- alias: Si CAST PLEX Alors Light 10
  trigger:
    platform: state
    entity_id: sensor.chromecast_state
    to: playing
  condition:
  - condition: state
    entity_id: media_player.denon_salon
    state: 'on'
  - condition: state
    entity_id: sensor.chromecast_source
    state: Plex
  action:
    service: scene.turn_on
    entity_id: scene.plexon
  
- alias: Si FIN PLEX Alors Light 100
  trigger:
    platform: state
    entity_id: sensor.chromecast_state
    to: idle
  condition:
  - condition: state
    entity_id: sensor.chromecast_source
    state: Plex
  action:
    service: scene.turn_on
    entity_id: scene.plexoff


- alias: Si PAUSE PLEX Alors Light 100
  trigger:
    platform: state
    entity_id: sensor.chromecast_state
    to: paused
  condition:
  - condition: state
    entity_id: sensor.chromecast_source
    state: Plex
  action:
    service: scene.turn_on
    entity_id: scene.plexoff


- alias: Si EXIT PLEX Alors Light 100
  trigger:
    platform: state
    entity_id: sensor.chromecast_state
    to: 'off'
  condition:
  - condition: template
    value_template: '{{ states.light.salon.attributes.brightness == "42" }}'
  action:
    service: scene.turn_on
    entity_id: scene.plexoff
  
####################################################################################
#                                                                                  #
#                                                                                  #
#                                SENSOR > LIGHTS                                   #
#                                                                                  #
#                                                                                  #
####################################################################################
  
- action:
  - data:
      entity_id: light.led_1
    service: light.turn_on
  alias: 'Allumer la LED si mouvement'
  condition:
  - condition: state
    entity_id: light.led_1
    state: 'off'
  trigger:
  - entity_id: sensor.motion_1
    from: standby
    platform: state
    to: motion detected

- action:
  - data:
      entity_id: light.led_1
    service: light.turn_off
  alias: 'Eteindre la LED si mouvement'
  condition:
  - condition: state
    entity_id: light.led_1
    state: 'on'
  trigger:
  - entity_id: sensor.motion_1
    from: motion detected
    platform: state
    to: standby
    for:
      hours: 0
      minutes: 0
      seconds: 2

- action:
    data:
      entity_id:
      - light.cuisine
    service: homeassistant.turn_on
  alias: 'Allumer la cuisine si mouvement'
  condition:
  - condition: state
    entity_id: light.cuisine
    state: 'off'
  - condition: numeric_state
    below: '300'
    entity_id: sensor.lumsens_1
  trigger:
  - entity_id: sensor.motion_1
    from: standby
    platform: state
    to: motion detected


- alias: 'Eteindre la lumière cuisine après 10min'
  trigger:
    platform: state
    entity_id: sensor.motion_1
    to: 'standby'
    for:
      minutes: 10
  action:
    service: homeassistant.turn_off
    entity_id: light.cuisine

#- alias: LED to RED quand temp sous 24
#  trigger:
#    platform: numeric_state
#    entity_id: sensor.temperature_1
#    below: 24
#  action:
#    service: homeassistant.turn_on
#    entity_id: light.led_1

- action:
    entity_id: light.salon
    service: homeassistant.turn_on
  alias: 'Allumer le salon si luminosité basse'
  condition:
  - condition: state
    entity_id: light.salon
    state: 'off'
  trigger:
  - platform: numeric_state
    below: '300'
    entity_id: sensor.lumsens_1