####################################################################################
#                                                                                  #
#                                                                                  #
#                                AUTOMATIONS                                       #
#                                                                                  #
#                                                                                  #
####################################################################################

- alias: 'Allumer les lumières au couché du soleil'
  initial_state: 'on'
  trigger:
    platform: sun
    event: sunset
    offset: -01:30:00
  condition:
    condition: or
    conditions:
      #Tracking OWNTRACK
      - condition: state
        entity_id: device_tracker.jungle_owntrack3t
        state: 'home'
      #Tracking DD-WRT
      - condition: state
        entity_id: device_tracker.androidf1562bd8cb4c4a91
        state: 'home'
  action:
    service: homeassistant.turn_on
    entity_id: light.salon

- alias: 'Allumer les lumières @ arrivée Home'
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: device_tracker.androidf1562bd8cb4c4a91
    to: 'home'
  condition:
    condition: numeric_state
    entity_id: sensor.lumsens_1
    below: '300'
  action:
    service: homeassistant.turn_on
    entity_id: light.salon, light.cuisine

####################################################################################
#                                                                                  #
#                                                                                  #
#                                PLEX & CAST                                       #
#                                                                                  #
#                                                                                  #
####################################################################################

- alias: Si CAST PLEX Alors Light 10
  trigger:
    platform: state
    entity_id: sensor.rasplex
    to: playing
  condition:
  - condition: state
    entity_id: sensor.chromecast_source
    state: 'Plex'
  action:
    service: scene.turn_on
    entity_id: scene.plexon

- alias: Si PAUSE PLEX Alors Light 70
  trigger:
    platform: state
    entity_id: sensor.rasplex
    to: paused
  condition:
  - condition: state
    entity_id: sensor.chromecast_source
    state: 'Plex'
  action:
    service: scene.turn_on
    entity_id: scene.plexpause

- alias: Si FIN PLEX Alors Light 100
  initial_state: 'off'
  trigger:
    platform: state
    entity_id: sensor.rasplex
    to: idle
    for:
      hours: 00
      minutes: 00
      seconds: 03
  action:
    service: scene.turn_on
    entity_id: scene.plexoff

####################################################################################
#                                                                                  #
#                                                                                  #
#                                SENSOR > LIGHTS                                   #
#                                                                                  #
#                                                                                  #
####################################################################################
  
- action:
  - data:
      entity_id: light.led_1
    service: light.turn_on
  alias: 'Allumer la LED si mouvement'
  condition:
  - condition: state
    entity_id: light.led_1
    state: 'off'
  trigger:
  - entity_id: sensor.motion_1
    from: standby
    platform: state
    to: motion detected

- action:
  - data:
      entity_id: light.led_1
    service: light.turn_off
  alias: 'Eteindre la LED si mouvement'
  condition:
  - condition: state
    entity_id: light.led_1
    state: 'on'
  trigger:
  - entity_id: sensor.motion_1
    from: motion detected
    platform: state
    to: standby
    for:
      hours: 0
      minutes: 0
      seconds: 2

- action:
    data:
      entity_id:
      - light.cuisine
    service: homeassistant.turn_on
  alias: 'Allumer la cuisine si mouvement'
  condition:
  - condition: state
    entity_id: light.cuisine
    state: 'off'
  - condition: numeric_state
    below: '300'
    entity_id: sensor.lumsens_1
  trigger:
  - entity_id: sensor.motion_1
    from: standby
    platform: state
    to: motion detected


- alias: 'Eteindre la lumière cuisine après 10min'
  trigger:
    platform: state
    entity_id: sensor.motion_1
    to: 'standby'
    for:
      minutes: 10
  action:
    service: homeassistant.turn_off
    entity_id: light.cuisine

- action:
    entity_id: light.salon
    service: homeassistant.turn_on
  alias: 'Allumer le salon si luminosité basse'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: light.salon
        state: 'off'
      - condition: or
        conditions:
         #Tracking OWNTRACK
          - condition: state
            entity_id: device_tracker.jungle_owntrack3t
            state: 'home'
          #Tracking DD-WRT
          - condition: state
            entity_id: device_tracker.androidf1562bd8cb4c4a91
            state: 'home'
  trigger:
  - platform: numeric_state
    below: '300'
    entity_id: sensor.lumsens_1

- action:
    entity_id: light.salon
    service: homeassistant.turn_off
  alias: 'Eteindre le salon si luminosité haute'
  condition:
      condition: or
      conditions:
        #Tracking OWNTRACK
        - condition: state
          entity_id: device_tracker.jungle_owntrack3t
          state: 'home'
        #Tracking DD-WRT
        - condition: state
          entity_id: device_tracker.androidf1562bd8cb4c4a91
          state: 'home'
  trigger:
  - platform: numeric_state
    above: '300'
    entity_id: sensor.lumsens_1
  initial_state: 'off'

- alias: Salon Light - Adjust Brightness
  trigger:
    platform: state
    entity_id: input_slider.salon_brightness
  action:
    - service: light.turn_on
# Note the use of 'data_template:' below rather than the normal 'data:' if you weren't using an input variable
      data_template:
        entity_id: light.salon
        brightness: '{{ trigger.to_state.state | int }}'

- alias: Cuisine Light - Adjust Brightness
  trigger:
    platform: state
    entity_id: input_slider.cuisine_brightness
  action:
    - service: light.turn_on
# Note the use of 'data_template:' below rather than the normal 'data:' if you weren't using an input variable
      data_template:
        entity_id: light.cuisine
        brightness: '{{ trigger.to_state.state | int }}'

- alias: 'Alerte pushbullet si 5° dehors'
  trigger:
    platform: numeric_state
    entity_id: sensor.yr_temperature
    below: '5'
  action:
    service: notify.pushbullet_3t
    data:
      title: 'Alerte GEL'
      message: 'Rentres les plantes, il va geler'