####################################################################################
#                                                                                  #
#                                                                                  #
#                                MEDIA CONTROL                                     #
#                                                                                  #
#                                                                                  #
####################################################################################

- alias: 'Media - Denon Chambre - Eteindre au départ'
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: device_tracker.androidf1562bd8cb4c4a91
    to: 'not_home'
  condition:
    condition: state
    entity_id: media_player.denon_chambre
    state: 'on'
  action:
    service: homeassistant.turn_off
    entity_id: media_player.denon_chambre

- alias: 'Media - PLEX - Baisser les lumières play'
  trigger:
    platform: state
    entity_id: sensor.rasplex
    to: playing
  condition:
  - condition: state
    entity_id: sensor.chromecast_source
    state: 'Plex'
  action:
    service: scene.turn_on
    entity_id: scene.plexon

- alias: 'Media - PLEX - Monter les lumières pause'
  trigger:
    platform: state
    entity_id: sensor.rasplex
    to: paused
  condition:
  - condition: state
    entity_id: sensor.chromecast_source
    state: 'Plex'
  action:
    service: scene.turn_on
    entity_id: scene.plexpause

- alias: 'Media - PLEX - Monter les lumières stop'
  initial_state: 'off'
  trigger:
    platform: state
    entity_id: sensor.rasplex
    to: idle
    for:
      hours: 00
      minutes: 00
      seconds: 03
  action:
    service: scene.turn_on
    entity_id: scene.plexoff

####################################################################################
#                                                                                  #
#                                                                                  #
#                                SENSOR > LIGHTS                                   #
#                                                                                  #
#                                                                                  #
####################################################################################

- alias: 'Lumières - Salon - Allumer au couché du soleil'
  initial_state: 'on'
  trigger:
    platform: sun
    event: sunset
    offset: -01:30:00
  condition:
    condition: or
    conditions:
      #Tracking OWNTRACK
      - condition: state
        entity_id: device_tracker.jungle_owntrack3t
        state: 'home'
      #Tracking DD-WRT
      - condition: state
        entity_id: device_tracker.androidf1562bd8cb4c4a91
        state: 'home'
  action:
    service: homeassistant.turn_on
    entity_id: light.salon

- alias: 'Lumières - Appartement - ON Arrivée Appart'
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: device_tracker.androidf1562bd8cb4c4a91
    to: 'home'
  condition:
    condition: numeric_state
    entity_id: sensor.lumsens_1
    below: '300'
  action:
    service: homeassistant.turn_on
    entity_id: light.salon, light.cuisine

- alias: 'Lumières - Appartement - OFF au Départ'
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: device_tracker.androidf1562bd8cb4c4a91
    to: 'not_home'
    # AJOUTER UN TRIGGER SI LAST MOTION ENTREE MOINS DE 2 MINUTE
  action:
    service: homeassistant.turn_off
    entity_id: light.salon, light.cuisine, light.vestibule

- alias: 'Lumières - Cuisine - ON mouvement'
  action:
    data:
      entity_id:
      - light.cuisine
    service: homeassistant.turn_on
  condition:
  - condition: state
    entity_id: light.cuisine
    state: 'off'
  - condition: numeric_state
    below: '300'
    entity_id: sensor.lumsens_1
  trigger:
  - entity_id: sensor.motion_1
    from: standby
    platform: state
    to: motion detected

- alias: 'Lumières - Cuisine - OFF mouvement 10min'
  trigger:
    platform: state
    entity_id: sensor.motion_1
    to: 'standby'
    for:
      minutes: 10
  action:
    service: homeassistant.turn_off
    entity_id: light.cuisine

- alias: 'Lumières - Vestibule - ON mouvement'
  action:
    data:
      entity_id:
      - light.vestibule
      color_temp: 263.0194634402946
    service: homeassistant.turn_on
  condition:
  - condition: state
    entity_id: light.vestibule
    state: 'off'
  trigger:
  - entity_id: sensor.motion_2
    from: standby
    platform: state
    to: motion detected

- alias: 'Lumières - Vestibule - OFF mouvement 10min'
  trigger:
    platform: state
    entity_id: sensor.motion_2
    to: 'standby'
    for:
      seconds: 30
  action:
    service: homeassistant.turn_off
    entity_id: light.vestibule

- alias: 'Lumières - Salon - ON si luminosité basse'
  action:
    entity_id: light.salon
    service: homeassistant.turn_on
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: light.salon
        state: 'off'
      - condition: or
        conditions:
         #Tracking OWNTRACK
          - condition: state
            entity_id: device_tracker.jungle_owntrack3t
            state: 'home'
          #Tracking DD-WRT
          - condition: state
            entity_id: device_tracker.androidf1562bd8cb4c4a91
            state: 'home'
  trigger:
  - platform: numeric_state
    below: '300'
    entity_id: sensor.lumsens_1

- alias: 'Lumières - Salon - OFF si luminosité haute'
  action:
    entity_id: light.salon
    service: homeassistant.turn_off
  condition:
      condition: or
      conditions:
        #Tracking OWNTRACK
        - condition: state
          entity_id: device_tracker.jungle_owntrack3t
          state: 'home'
        #Tracking DD-WRT
        - condition: state
          entity_id: device_tracker.androidf1562bd8cb4c4a91
          state: 'home'
  trigger:
  - platform: numeric_state
    above: '300'
    entity_id: sensor.lumsens_1
  initial_state: 'off'

####################################################################################
#                                                                                  #
#                                                                                  #
#                                LIGHT SCENES                                      #
#                                                                                  #
#                                                                                  #
####################################################################################

- alias: 'Lumières - Vestibule - Physchedelic scene'
  trigger:
    platform: event
    event_type: call_service
    event_data:
      service_data:
        entity_id: scene.psychedelic
      domain: scene
      service: turn_on
  action:
    entity_id: light.vestibule
    service: light.turn_on
    data:
     rgb_color: [46,0,137]

####################################################################################
#                                                                                  #
#                                                                                  #
#                                ALERTES                                           #
#                                                                                  #
#                                                                                  #
####################################################################################

- alias: 'Alerte - Pushbullet - Gel à venir'
  trigger:
    platform: numeric_state
    entity_id: sensor.yr_temperature
    below: '5'
  action:
    service: notify.pushbullet_3t
    data:
      title: 'Alerte GEL'
      message: 'Rentres les plantes, il va geler'

####################################################################################
#                                                                                  #
#                                                                                  #
#                                PC CONTROL                                        #
#                                                                                  #
#                                                                                  #
####################################################################################

- alias: junglepc_redemarrer
  trigger:
    platform: state
    entity_id: input_select.pcoptions
    to: "Redémarrer"
  action:
    - service: shell_command.restart_z800
    - service: input_select.select_option
      entity_id: input_select.pcoptions
      data_template:
        option: "Choisir une action"

- alias: junglepc_eteindre
  trigger:
    platform: state
    entity_id: input_select.pcoptions
    to: "Eteindre"
  action:
    - service: shell_command.shutdown_z800
    - service: input_select.select_option
      entity_id: input_select.pcoptions
      data_template:
        option: "Choisir une action"

- alias: junglepc_veille
  trigger:
    platform: state
    entity_id: input_select.pcoptions
    to: "Veille"
  action:
    - service: shell_command.sleep_z800
    - service: input_select.select_option
      entity_id: input_select.pcoptions
      data_template:
        option: "Choisir une action"

- alias: 'PC - Arrêter au départ'
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: device_tracker.androidf1562bd8cb4c4a91
    to: 'not_home'
  condition:
    condition: state
    entity_id: switch.jungle_pc
    state: 'on'
  action:
    service: homeassistant.turn_off
    entity_id: switch.jungle_pc

####################################################################################
#                                                                                  #
#                                                                                  #
#                                HARMONY HUB                                       #
#                                                                                  #
#                                                                                  #
####################################################################################

- alias: Harmony
  hide_entity: True
  trigger:
    platform: state
    entity_id: input_select.harmony
    from: 'Choisir la source'
  action:
    - service: remote.turn_on
      entity_id: remote.hub_salon
      data_template:
        activity: >
          {% if is_state("input_select.harmony", "Chromecast") %}
            27262320
          {% elif is_state("input_select.harmony", "Chambre Bluetooth") %}
            28429925
          {% elif is_state("input_select.harmony", "Vinyle") %}
            28532020
          {% else %}
          {% endif %}
    - service: input_select.select_option
      entity_id: input_select.harmony
      data_template:
        option: "Choisir la source"

- alias: Harmony Off
  hide_entity: True
  trigger:
    platform: state
    entity_id: input_select.harmony
    to: 'Arrêt'
  action:
    - service: remote.turn_off
      entity_id: remote.hub_salon
    - service: input_select.select_option
      entity_id: input_select.harmony
      data_template:
        option: "Choisir la source"

####################################################################################
#                                                                                  #
#                                                                                  #
#                                HEATING                                           #
#                                                                                  #
#                                                                                  #
####################################################################################
        
- alias: 'Chauffage - Salon - 22 Arrivée Appart'
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: device_tracker.androidf1562bd8cb4c4a91
    to: 'home'
    # AJOUTER UN TRIGGER SI LAST MOTION ENTREE MOINS DE 2 MINUTE
  action:
    service: climate.set_temperature
    data:
        entity_id: climate.salon
        temperature: '22'

- alias: 'Chauffage - Salon - 17 Départ Appart'
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: device_tracker.androidf1562bd8cb4c4a91
    to: 'not_home'
    # AJOUTER UN TRIGGER SI LAST MOTION ENTREE MOINS DE 2 MINUTE
  action:
    - service: climate.set_temperature
      data:
        entity_id: climate.salon
        temperature: '17'
    - service : homeassistant.turn_off
      data:
        entity_id: switch.radiateur_salon

- alias: 'Chauffage - Salon - 17 et OFF le soir'
  initial_state: 'on'
  trigger:
    platform: time
    hours: 23
    minutes: 30
    seconds: 0
  condition:
    - condition: state
      entity_id: device_tracker.androidf1562bd8cb4c4a91
      state: 'home'
  action:
    - service: climate.set_temperature
      data:
        entity_id: climate.salon
        temperature: '17'
    - service : homeassistant.turn_off
      data:
        entity_id: switch.radiateur_salon

- alias: 'Chauffage - Salon - 22 et ON le matin semaine'
  initial_state: 'on'
  trigger:
    platform: time
    hours: 8
    minutes: 0
    seconds: 0
  condition:
    - condition: state
      entity_id: device_tracker.androidf1562bd8cb4c4a91
      state: 'home'
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
  action:
    - service: climate.set_temperature
      data:
        entity_id: climate.salon
        temperature: '22'
    - service : homeassistant.turn_on
      data:
        entity_id: switch.radiateur_salon

####################################################################################
#                                                                                  #
#                                                                                  #
#                                LIGHT SLIDERS                                     #
#                                                                                  #
#                                                                                  #
####################################################################################

- alias: 'InputSlider - Salon - Luminosité'
  trigger:
    platform: state
    entity_id: input_slider.salon_brightness
  action:
    - service: light.turn_on
      # Note the use of 'data_template:' below rather than the normal 'data:' if you weren't using an input variable
      data_template:
        entity_id: light.salon
        brightness: '{{ trigger.to_state.state | int }}'

- alias: 'InputSlider - Cuisine - Luminosité'
  trigger:
    platform: state
    entity_id: input_slider.cuisine_brightness
  action:
    - service: light.turn_on
      # Note the use of 'data_template:' below rather than the normal 'data:' if you weren't using an input variable
      data_template:
        entity_id: light.cuisine
        brightness: '{{ trigger.to_state.state | int }}'

- alias: 'InputSlider - Vestibule - Luminosité'
  trigger:
    platform: state
    entity_id: input_slider.vestibule_brightness
  action:
    - service: light.turn_on
      # Note the use of 'data_template:' below rather than the normal 'data:' if you weren't using an input variable
      data_template:
        entity_id: light.vestibule
        brightness: '{{ trigger.to_state.state | int }}'
