####################################################################################
#                                                                                  #
#                                                                                  #
#                                INTRO                                             #
#                                                                                  #
#                                                                                  #
####################################################################################

homeassistant:
  name: Jungle'Home
  latitude: !secret latitude_
  longitude: !secret longitude_
  elevation: 80
  unit_system: metric
  time_zone: Europe/Paris
  
http:
  api_password: !secret api_ha

####################################################################################
#                                                                                  #
#                                                                                  #
#                                INCLUDES                                          #
#                                                                                  #
#                                                                                  #
####################################################################################

group: !include groups.yaml
automation: !include automations.yaml
sensor: !include sensors.yaml
scene: !include scenes.yaml

####################################################################################
#                                                                                  #
#                                                                                  #
#                                COMPONENTS                                        #
#                                                                                  #
#                                                                                  #
####################################################################################

frontend:
logger:
  default: error
  logs:
    DenonAVR: fatal
config:
updater:
discovery:
mqtt:  
  broker: 192.168.1.132
  port: 1883
  username: !secret mqtt_login_junglenas
  password: !secret mqtt_password_junglenas
conversation:
history:
logbook:
sun:
light:
  - platform: lifx
  - platform: mqtt_json  
    name: "LED 1"  
    state_topic: "jungle/sensornode1"  
    command_topic: "jungle/sensornode1/set"  
    brightness: true  
    flash: true  
    rgb: true  
    optimistic: false  
    qos: 0
media_player:
  - platform: cast
  - platform: denonavr
    host: 192.168.1.135
    name: Denon Salon
    show_all_sources: False
    zones:
      - zone: Zone2
        name: Denon Chambre
device_tracker:
  - platform: ddwrt
    host: 192.168.1.1
    username: admin 
    password: !secret router_password
  - platform: gpslogger
camera:
  - platform: generic
    name: Jungle 3T
    still_image_url: https://maps.googleapis.com/maps/api/staticmap?center={{ states.device_tracker.d55a7c08.attributes.latitude }},{{ states.device_tracker.d55a7c08.attributes.longitude }}&zoom=13&size=500x500&maptype=roadmap&markers=color:blue%7Clabel:P%7C{{ states.device_tracker.d55a7c08.attributes.latitude }},{{ states.device_tracker.d55a7c08.attributes.longitude }}
    limit_refetch_to_url_change: true
  - platform: generic
    name: Meteo Epinay sur Orge
    still_image_url: https://www.yr.no/place/France/Île-de-France/Épinay-sur-Orge/meteogram.svg
    content_type: 'image/svg+xml'