####################################################################################
#                                                                                  #
#                                                                                  #
#                                INTRO                                             #
#                                                                                  #
#                                                                                  #
####################################################################################

homeassistant:
  name: Jungle'Home
  latitude: !secret latitude_home
  longitude: !secret longitude_home
  elevation: 80
  unit_system: metric
  time_zone: Europe/Paris
  customize: !include customize.yaml

http:
  api_password: !secret api_ha

####################################################################################
#                                                                                  #
#                                                                                  #
#                                INCLUDES                                          #
#                                                                                  #
#                                                                                  #
####################################################################################

group: !include groups.yaml
automation: !include automations.yaml
sensor: !include sensors.yaml
scene: !include scenes.yaml
zone: !include zones.yaml
input_slider: !include input_sliders.yaml

####################################################################################
#                                                                                  #
#                                                                                  #
#                                COMPONENTS                                        #
#                                                                                  #
#                                                                                  #
####################################################################################

frontend:
logger:
  default: error
  logs:
    DenonAVR: fatal
config:
updater:
discovery:
mqtt:  
  broker: 192.168.1.132
  port: 1883
  username: !secret mqtt_login_junglenas
  password: !secret mqtt_password_junglenas
conversation:
history:
logbook:
  exclude:
    entities:
      - sensor.rpi_uptime
notify:
  - name: pushbullet_3t
    platform: pushbullet
    api_key: !secret pushbullet_api
sun:
light:
  - platform: lifx
  - platform: mqtt_json  
    name: "LED 1"  
    state_topic: "jungle/sensornode1"  
    command_topic: "jungle/sensornode1/set"  
    brightness: true  
    flash: true  
    rgb: true  
    optimistic: false  
    qos: 0
media_player:
  - platform: cast
  - platform: denonavr
    host: 192.168.1.136
    name: Denon Salon
    show_all_sources: False
    zones:
      - zone: Zone2
        name: Denon Chambre
device_tracker:
  - platform: ddwrt
    host: 192.168.1.1
    username: admin 
    password: !secret router_password
  - platform: gpslogger
  - platform: owntracks
    max_gps_accuracy: 200
camera:
  - platform: generic
    name: Meteo Epinay sur Orge
    still_image_url: https://www.yr.no/place/France/Île-de-France/Épinay-sur-Orge/meteogram.svg
    content_type: 'image/svg+xml'