####################################################################################
#                                                                                  #
#                                                                                  #
#                                INTRO                                             #
#                                                                                  #
#                                                                                  #
####################################################################################

homeassistant:
  name: Jungle'Home
  latitude: !secret latitude_home
  longitude: !secret longitude_home
  elevation: 80
  unit_system: metric
  time_zone: Europe/Paris
  customize: !include customize.yaml

http:
  api_password: !secret api_ha
  ssl_certificate: /etc/letsencrypt/live/jungleman.house/fullchain.pem
  ssl_key: /etc/letsencrypt/live/jungleman.house/privkey.pem

####################################################################################
#                                                                                  #
#                                                                                  #
#                                INCLUDES                                          #
#                                                                                  #
#                                                                                  #
####################################################################################

group: !include groups.yaml
automation: !include automations.yaml
sensor: !include sensors.yaml
scene: !include scenes.yaml
zone: !include zones.yaml
input_slider: !include input_sliders.yaml
switch: !include switches.yaml
input_select: !include input_selects.yaml

####################################################################################
#                                                                                  #
#                                                                                  #
#                                COMPONENTS                                        #
#                                                                                  #
#                                                                                  #
####################################################################################

frontend:
logger:
  default: error
  logs:
    DenonAVR: fatal
config:
updater:
discovery:
mqtt:  
  broker: 192.168.1.132
  port: 1883
  username: !secret mqtt_login_junglenas
  password: !secret mqtt_password_junglenas
conversation:
history:
logbook:
  exclude:
    entities:
      - sensor.rpi_uptime
      - group.cuisine
      - group.salon
      - group.lumieres_home
      - light.led_1
      - sensor.time
      - sensor.yr_symbol
      - sensor.yr_temperature
      - sensor.yr_cloudiness
      - sensor.yr_humidity
      - sensor.yr_precipitation
      - sensor.yr_wind_speed
      - sensor.yr_wind_direction
notify:
  - name: pushbullet_3t
    platform: pushbullet
    api_key: !secret pushbullet_api
sun:
light:
  - platform: lifx
  - platform: yeelight
    devices:
      192.168.1.137:
        name: Chambre
        transition: 1000
  - platform: mqtt_json  
    name: "LED 1"  
    state_topic: "jungle/sensornode1"  
    command_topic: "jungle/sensornode1/set"  
    brightness: true  
    flash: true  
    rgb: true  
    optimistic: false  
    qos: 0
media_player:
  - platform: cast
  - platform: denonavr
    host: 192.168.1.136
    name: Denon Salon
    show_all_sources: False
    zones:
      - zone: Zone2
        name: Denon Chambre
device_tracker:
  - platform: ddwrt
    host: 192.168.1.1
    username: admin 
    password: !secret router_password
  - platform: gpslogger
  - platform: owntracks
    max_gps_accuracy: 200
camera:
  - platform: generic
    name: Meteo Epinay sur Orge
    still_image_url: https://www.yr.no/place/France/Île-de-France/Épinay-sur-Orge/meteogram.svg
    content_type: 'image/svg+xml'
    
remote:
  - platform: harmony
    name: 'HUB Salon'
    host: 192.168.1.148
    port: 5222
    activity: 'Regarder la TV'
    #username: !secret harmony_mail
    #password: !secret harmony_password
    
####################################################################################
#                                                                                  #
#                                                                                  #
#                                BINARY SENSORS                                    #
#                                                                                  #
#                                                                                  #
####################################################################################

#http://ipESP/control?cmd=GPIO,12,1

climate:
  - platform: generic_thermostat
    name: Salon
    heater: switch.radiateur_salon
    target_sensor: sensor.temperature_1
    min_temp: 17
    max_temp: 25
    target_temp: 21
    tolerance: 1
    min_cycle_duration:
      seconds: 5
    keep_alive:
      minutes: 3

####################################################################################
#                                                                                  #
#                                                                                  #
#                                PC CONTROL                                        #
#                                                                                  #
#                                                                                  #
####################################################################################

shell_command:
  shutdown_z800: 'curl -k http://jungle-pc:8000/?action=System.Shutdown'
  restart_z800: 'curl -k http://jungle-pc:8000/?action=System.Restart'
  sleep_z800: 'curl -k http://jungle-pc:8000/?action=System.Sleep'

