####################################################################################
#                                                                                  #
#                                                                                  #
#                                INTRO                                             #
#                                                                                  #
#                                                                                  #
####################################################################################

homeassistant:
  name: !secret name_home
  latitude: !secret latitude_home
  longitude: !secret longitude_home
  elevation: !secret elevation_home
  unit_system: metric
  time_zone: !secret time_zone_home
  customize: !include customize.yaml
  packages: !include_dir_named packages
  
http:
  base_url: !secret ha_url
  
recorder:
  purge_keep_days: 5
  
mobile_app:

####################################################################################
#                                                                                  #
#                                                                                  #
#                                INCLUDES                                          #
#                                                                                  #
#                                                                                  #
####################################################################################

group: !include_dir_merge_named groups/

#Automation Editor
automation: !include automations.yaml
#Legacy automations in dir
automation old: !include_dir_merge_list automations/

frontend:
  themes: !include themes.yaml

####################################################################################
#                                                                                  #
#                                                                                  #
#                                MAIN CONFIG                                       #
#                                                                                  #
#                                                                                  #
####################################################################################

logger:
  default: warn
#  logs:
#    pydeconz: debug
#    homeassistant.components.deconz: debug  

config:

updater:
  reporting: False
  
discovery:
  ignore:
    - harmony
    - yeelight
    
system_health:

map:

history:
  include:
    domains:
      - sensor
      - media_player
      - light
      - device_tracker
      - sun
  exclude:
    entities:
      - sensor.alarm_time
      - sensor.breaches_contactjunglemanfr
      - sensor.breaches_mikaelboulogmailcom
      - sensor.date
      - sensor.finlande
      - sensor.france
      - sensor.turquie
      - sensor.gmail_imap
      - sensor.hp_ilo_nom_du_serveur
      - sensor.ipv4_address_eth0
      - sensor.rpi_uptime
      - sensor.sonarr_queue
      - sensor.sonarr_upcoming
      - sensor.sonarr_wanted
      - sensor.time
      - sensor.transmission_active_torrents
      - sensor.transmission_status
      - sensor.yr_symbol
      - media_player.junglekodi
      
logbook:
  exclude:
    entities:
      - sensor.time
      - sensor.alarm_time
      - sensor.rpi_uptime
      - group.cuisine
      - group.salon
      - group.lumieres_home
      - sensor.time
      - sensor.yr_symbol
      - sensor.yr_temperature
      - sensor.yr_cloudiness
      - sensor.yr_humidity
      - sensor.yr_precipitation
      - sensor.yr_wind_speed
      - sensor.yr_wind_direction
      - sensor.france
      - sensor.finlande
      - sensor.turquie
      - sensor.transmission_status
      - sensor.gmail_imap
      - sensor.rasplex
      - sensor.chromecast_source
      - sensor.chromecast_state
      - sensor.transmission_active_torrents
      - sensor.transmission_down_speed
      - sensor.transmission_up_speed
      - binary_sensor.gmail_new
      - media_player.junglehomemini
      - media_player.jungletv
      - media_player.junglekodi
      - automation.keep_google_home_alive
      - automation.edf_calcul_cout_journalier
      - automation.edf_remise_a_zero_journalier
      - automation.reveil_send_tasker_event
      - sensor.cout_wh_instant
      - sensor.releve_consommation_wh
      - sensor.cout_journalier
      - sensor.cout_journalier_view
      - sensor.hp_edf_view
      - weather.yweather
