####################################################################################
#                                                                                  #
#                                                                                  #
#                                SENSORS                                           #
#                                                                                  #
#                                                                                  #
####################################################################################

- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /home
    - type: memory_free
    - type: processor_use
    - type: ipv4_address
      arg: eth0
- platform: yr
    - symbol
    - temperature
    - precipitation
    - windSpeed
    - windDirection
    - humidity
    - cloudiness
- platform: time_date
  display_options:
    - 'time'
    - 'date'
    #- 'date_time'
    #- 'time_date'
    #- 'time_utc'
    #- 'beat'
- platform: moon
- platform: template
  sensors:
    chromecast_source:
      value_template: '{{ states.media_player.junglecast.attributes["app_name"] }}'
      friendly_name: 'Chromecast Source'
    chromecast_state:
      value_template: '{{ states.media_player.junglecast.state }}'
      friendly_name: 'Chromecast State'  
  
####################################################################################
#                                                                                  #
#                                                                                  #
#                                SENSOR NODES                                      #
#                                                                                  #
#                                                                                  #
####################################################################################

- platform: mqtt  
  state_topic: "jungle/sensornode1"  
  name: "Humidite 1"  
  unit_of_measurement: "%"  
  value_template: '{{ value_json.humidity | round(1) }}'  
- platform: mqtt  
  state_topic: "jungle/sensornode1"  
  name: "LumSens 1"
  ##This sensor is not calibrated to actual LUX. Rather, this a map of the input voltage ranging from 0 - 1023.
  unit_of_measurement: "LUX"  
  value_template: '{{ value_json.ldr }}'  
- platform: mqtt  
  state_topic: "jungle/sensornode1"  
  name: "Motion 1"  
  value_template: '{{ value_json.motion }}'  
- platform: mqtt  
  state_topic: "jungle/sensornode1"  
  name: "Temperature 1"  
  unit_of_measurement: "°F"
  value_template: '{{ value_json.temperature | round(1) }}'
- platform: mqtt
  state_topic: "jungle/sensornode1"
  name: "Real Feel 1"
  unit_of_measurement: "°F"
  value_template: '{{ value_json.heatIndex | round(1) }}'