- platform: mqtt
  name: "Radiateur Salon"  
  state_topic: "jungle/radcontrol1/#"  
  command_topic: "jungle/radcontrol1/set"
  payload_on: "1"
  payload_off: "0"  
  qos: 0
  optimistic: false