- platform: mqtt
  name: "Radiateur Salon"  
  state_topic: "jungle/radcontrol1/#"
  # RETAIN FLAG peut etre trop court si reboot HA alors switch ON par defaut
  command_topic: "jungle/radcontrol1/set"
  payload_on: "1"
  payload_off: "0"  
  qos: 0
  optimistic: false
- platform: wake_on_lan
  mac_address: "44-8A-5B-CC-56-C5"
  name: "Jungle PC"
  host: "JUNGLE-PC"
  turn_off:
    service: shell_command.shutdown_z800