- alias: 'Volet Appartement Fermer tombee nuit'
  initial_state: 'off'
  trigger:
    platform: sun
    event: sunset
    offset: "-00:15:00"
  condition:
    - condition: state
      entity_id: binary_sensor.door_window_sensor_158d00019fd569
      state: 'off'
    - condition: state
      entity_id: binary_sensor.door_window_sensor_158d0001f381a2
      state: 'on'
  action:
    - service: cover.close_cover
      entity_id: cover.volet_du_salon
- alias: 'Volet Appartement Ouvrir journee si absent'
  initial_state: 'off'
  trigger:
    platform: sun
    event: sunrise
  condition:
    - condition: state
      entity_id: device_tracker.jungle3t_wifi
      state: 'not_home'
    - condition: state
      entity_id: binary_sensor.door_window_sensor_158d0001f381a2
      state: 'off'
  action:
    - service: cover.open_cover
      entity_id: cover.volet_du_salon
- alias: 'Volet Appartement Ouvrir volet a ouverture fenetre'
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: binary_sensor.door_window_sensor_158d00019fd569
    to: 'on'
  condition:
    - condition: state
      entity_id: device_tracker.jungle3t_wifi
      state: 'home'
    - condition: state
      entity_id: binary_sensor.door_window_sensor_158d0001f381a2
      state: 'off'
  action:
    - service: cover.open_cover
      entity_id: cover.volet_du_salon