- alias: 'Lumières - Vestibule - ON mouvement'
  initial_state: 'on'
  action:
    data:
      entity_id:
      - light.vestibule
      color_temp: 263.0194634402946
    service: homeassistant.turn_on
  condition:
  - condition: state
    entity_id: light.vestibule
    state: 'off'
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_158d0001ad6284
    from: 'off'
    to: 'on'
- alias: 'Lumières - Vestibule - OFF mouvement 10min'
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_158d0001ad6284
    from: 'on'
    to: 'off'
    for:
      seconds: 40
  action:
    service: scene.turn_on
    entity_id: scene.vestibuleoff
- alias: 'Lumières - Vestibule - Physchedelic scene'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: call_service
    event_data:
      service_data:
        entity_id: scene.psychedelic
      domain: scene
      service: turn_on
  action:
    entity_id: light.vestibule
    service: light.turn_on
    data:
     rgb_color: [46,0,137]
- alias: 'Lumières - Vestibule - Coolblue scene'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: call_service
    event_data:
      service_data:
        entity_id: scene.coolblue
      domain: scene
      service: turn_on
  action:
    entity_id: light.vestibule
    service: light.turn_on
    data:
     rgb_color: [46,0,137]
- alias: 'Lumières - Vestibule - Chaud scene'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: call_service
    event_data:
      service_data:
        entity_id: scene.chaud
      domain: scene
      service: turn_on
  action:
    entity_id: light.vestibule
    service: light.turn_off
- alias: 'Lumières - Vestibule - ON porte ouverte'
  initial_state: 'on'
  action:
    data:
      entity_id:
      - light.vestibule
      color_temp: 263.0194634402946
    service: homeassistant.turn_on
  trigger:
    platform: state
    entity_id: binary_sensor.door_window_sensor_158d00019fd4b5
    from: 'off'
    to: 'on'
- alias: 'Lumières - Vestibule - OFF porte fermee'
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_158d0001ad6284
    from: 'on'
    to: 'off'
    for:
      minutes: 5
  action:
    service: light.turn_off
    entity_id: light.vestibule