- alias: Cube event rotate
  trigger:
    platform: event
    event_type: cube_action
    event_data:
      entity_id: binary_sensor.cube_158d000103a40c
      action_type: rotate
  action:
    - service: media_player.volume_set
      data_template:
        entity_id: media_player.denon_salon
        volume_level: >
          {% if trigger.event.data.action_value | float > 0 %}
          {{ (states.media_player.denon_salon.attributes.volume_level + 0.03)| float | round(2) }}
          {% else %}
          {{ (states.media_player.denon_salon.attributes.volume_level - 0.03)| float | round(2) }}
          {% endif %}
- alias: Cube event shake_air
  trigger:
    platform: event
    event_type: cube_action
    event_data:
      entity_id: binary_sensor.cube_158d000103a40c
      action_type: shake_air
  action:
    - service: media_player.media_next_track
      entity_id: media_player.la_tele
    - service: media_player.volume_set
      entity_id: media_player.junglehomemini
      data:
        volume_level: 0.3
    - service: tts.google_say
      entity_id: media_player.junglehomemini
      data:
        message: 'Okay next'
        language: 'en'
- alias: Cube event flip90
  trigger:
    platform: event
    event_type: cube_action
    event_data:
      entity_id: binary_sensor.cube_158d000103a40c
      action_type: flip90
  action:
    - service: light.turn_on
      entity_id: light.salon
      data_template:
        brightness: '{{states.light.salon.attributes.brightness + 40}}'
        transition: 3
- alias: Cube event flip180
  trigger:
    platform: event
    event_type: cube_action
    event_data:
      entity_id: binary_sensor.cube_158d000103a40c
      action_type: flip180
  action:
    - service: light.turn_on
      entity_id: light.salon
      data_template:
        brightness: '{{states.light.salon.attributes.brightness - 40}}'
        transition: 3
- alias: Cube event tap_twice
  trigger:
    platform: event
    event_type: cube_action
    event_data:
      entity_id: binary_sensor.cube_158d000103a40c
      action_type: tap_twice
  action:
    - service: media_player.volume_mute
      data_template:
        entity_id: media_player.denon_salon
        is_volume_muted: >-
          {%- if states.media_player.denon_salon.attributes.is_volume_muted == false -%}
          true
          {%- else -%}
          false
          {%- endif -%}
    - service: media_player.volume_mute
      data_template:
        entity_id: media_player.denon_bureau
        is_volume_muted: >-
          {%- if states.media_player.denon_bureau.attributes.is_volume_muted == false -%}
          true
          {%- else -%}
          false
          {%- endif -%}
- alias: TTS - GoogleHome - nouveau mail
  trigger:
    platform: numeric_state
    entity_id: sensor.gmail_imap
    above: 0
  condition:
    - condition: state
      entity_id: device_tracker.jungle3t_wifi
      state: 'home'
    - condition: time
      after: '10:00'
      before: '22:00'
  action:
    - service: media_player.volume_set
      entity_id: media_player.junglehomemini
      data:
        volume_level: 0.3
    - service: tts.google_say
      entity_id: media_player.junglehomemini
      data:
        message: 'Jinjeul, tu as reçu un mail !'
        language: 'fr'     
- alias: TTS - GoogleHome - keupon arrive
  trigger:
    platform: state
    entity_id: binary_sensor.door_window_sensor_158d00019fd4b5
    to: 'on'
  condition: 
    condition: and
    conditions:
      - condition: state
        entity_id: device_tracker.keupon_huawei
        state: 'home'
      - condition: template
        value_template: '{{(as_timestamp(now())-as_timestamp(states.device_tracker.keupon_huawei.last_updated)) < 300 }}'
  action:
    - service: media_player.volume_set
      entity_id: media_player.junglehomemini
      data:
        volume_level: 0.3
    - service: media_player.play_media
      entity_id: media_player.junglehomemini
      data:
        media_content_id: !secret url_mp3_waza
        media_content_type: music
    - delay: 00:00:05
    - service: tts.google_say
      entity_id: media_player.junglehomemini
      data:
        message: 'Monsieur Keupon est dans la place !'
        language: 'fr'

