- alias: Cube event rotate
  trigger:
    platform: event
    event_type: xiaomi_aqara.cube_action
    event_data:
      entity_id: binary_sensor.cube_158d000103a40c
      action_type: rotate
  action:
    - service: media_player.volume_set
      data_template:
        entity_id: media_player.denon_salon
        volume_level: >
          {% if trigger.event.data.action_value | float > 0 %}
          {{ (states.media_player.denon_salon.attributes.volume_level + 0.03)| float | round(2) }}
          {% else %}
          {{ (states.media_player.denon_salon.attributes.volume_level - 0.03)| float | round(2) }}
          {% endif %}
- alias: Cube event shake_air
  trigger:
    platform: event
    event_type: xiaomi_aqara.cube_action
    event_data:
      entity_id: binary_sensor.cube_158d000103a40c
      action_type: shake_air
  action:
    - service: media_player.media_next_track
      entity_id: media_player.jungletv
    - service: media_player.volume_set
      entity_id: media_player.junglehomemini
      data:
        volume_level: 0.3
    - service: tts.google_say
      entity_id: media_player.junglehomemini
      data:
        message: 'Okay next'
        language: 'en'
- alias: Cube event flip90
  trigger:
    platform: event
    event_type: xiaomi_aqara.cube_action
    event_data:
      entity_id: binary_sensor.cube_158d000103a40c
      action_type: flip90
  action:
    - service: light.turn_on
      entity_id: light.salon
      data_template:
        brightness: '{{states.light.salon.attributes.brightness + 40}}'
        transition: 3
- alias: Cube event flip180
  trigger:
    platform: event
    event_type: xiaomi_aqara.cube_action
    event_data:
      entity_id: binary_sensor.cube_158d000103a40c
      action_type: flip180
  action:
    - service: light.turn_on
      entity_id: light.salon
      data_template:
        brightness: '{{states.light.salon.attributes.brightness - 40}}'
        transition: 3
- alias: Cube event tap_twice
  trigger:
    platform: event
    event_type: xiaomi_aqara.cube_action
    event_data:
      entity_id: binary_sensor.cube_158d000103a40c
      action_type: tap_twice
  action:
    - service: media_player.volume_mute
      data_template:
        entity_id: media_player.denon_salon
        is_volume_muted: >-
          {%- if states.media_player.denon_salon.attributes.is_volume_muted == false -%}
          true
          {%- else -%}
          false
          {%- endif -%}
    - service: media_player.volume_mute
      data_template:
        entity_id: media_player.denon_bureau
        is_volume_muted: >-
          {%- if states.media_player.denon_bureau.attributes.is_volume_muted == false -%}
          true
          {%- else -%}
          false
          {%- endif -%}