- alias: 'Alarme - Pushbullet - Fenetre ouverte'
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: binary_sensor.door_window_sensor_158d00019fd569
    to: 'on'
  condition:
    - condition: state
      entity_id: input_boolean.vacancesstate
      state: 'on'
  action:
    service: notify.pushbullet_3t
    data:
      title: 'ALARME'
      message: 'Porte Fenetre a été ouverte !'
- alias: 'Alarme - Pushbullet - Porte ouverte'
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: binary_sensor.door_window_sensor_158d00019fd4b5
    to: 'on'
  condition:
    - condition: state
      entity_id: input_boolean.vacancesstate
      state: 'on'
  action:
    service: notify.pushbullet_3t
    data:
      title: 'ALARME'
      message: 'Porte Entrée a été ouverte !'