- alias: 'Alarme - Vacances - Activé'
  trigger:
    platform: state
    entity_id: input_boolean.vacancesstate
    to: 'on'
  action:
    - service: automation.turn_off
      entity_id: group.light_automation, group.media_automation, group.chauffage_automation, group.scene_automation, group.reveil_automation
    - service: automation.turn_on
      entity_id: automation.update_homeassistant_disponible, automation.power__server__bring_it_back_up
- alias: 'Alarme - Vacances - Désactivé'
  trigger:
    platform: state
    entity_id: input_boolean.vacancesstate
    to: 'off'
  action:
    - service: automation.turn_on
      entity_id: group.light_automation, group.media_automation, group.chauffage_automation, group.scene_automation, group.reveil_automation
    - service: automation.turn_off
      entity_id: automation.lumieres__salon__allumer_soir