- alias: 'Alerte Pushbullet Gel à venir'
  initial_state: 'off'
  trigger:
    platform: numeric_state
    entity_id: sensor.yr_temperature
    below: '5'
  action:
    service: notify.pushbullet_3t
    data:
      title: 'Alerte GEL'
      message: 'Rentres les plantes, il va geler'
- alias: 'Alerte Pushbullet I have been pwned contactjunglemanfr'
  initial_state: 'on'
  trigger:
    platform: numeric_state
    entity_id: sensor.breaches_contactjunglemanfr
    above: 0
  action:
    service: notify.pushbullet_3t
    data:
      title: 'Fuite de donnée détectée'
      message: 'contact@jungleman.fr'
- alias: 'Alerte Pushbullet I have been pwned mikaelboulogmailcom'
  initial_state: 'on'
  trigger:
    platform: numeric_state
    entity_id: sensor.breaches_contactjunglemanfr
    above: 2
  action:
    service: notify.pushbullet_3t
    data:
      title: 'Fuite de donnée détectée'
      message: 'mikael.boulo@gmail.com'
- alias: 'Alerte Pushbullet Glances JungleNAS down'
  initial_state: 'off'
  trigger:
    platform: state
    entity_id: sensor.glances_running
    from: '1'
    to: 'unavailable'
    for:
      minutes: 1
    # Mesuré 30 secondes après coupure du service glances
  action:
    service: notify.pushbullet_3t
    data:
      title: 'Monitoring'
      message: 'JungleNAS semble être éteint !'
- alias: 'Alerte Pushbullet Glances JungleNAS back'
  initial_state: 'off'
  trigger:
    platform: state
    entity_id: sensor.glances_running
    from: 'unavailable'
    # Mesuré 15 secondes après retour du service glances
  action:
    service: notify.pushbullet_3t
    data:
      title: 'Monitoring'
      message: 'JungleNAS est de retour !'
- alias: 'Alerte Pushbullet Portail terrasses ouvert'
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: switch.portail
  action:
    service: notify.pushbullet_3t
    data:
      title: 'Appartement Terrasses'
      message: 'Le portail a été ouvert'
- alias: 'Alerte Pushbullet Volet Ouvert'
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: binary_sensor.door_window_sensor_158d0001f381a2
    to: 'on'
  condition:
    - condition: state
      entity_id: device_tracker.jungle3t_wifi
      state: 'not_home'
  action:
    service: notify.pushbullet_3t
    data:
      title: 'Appartement Terrasses'
      message: 'Volet du salon OUVERT'
- alias: 'Alerte Pushbullet Volet Fermé'
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: binary_sensor.door_window_sensor_158d0001f381a2
    to: 'off'
  condition:
    - condition: state
      entity_id: device_tracker.jungle3t_wifi
      state: 'not_home'
  action:
    service: notify.pushbullet_3t
    data:
      title: 'Appartement Terrasses'
      message: 'Volet du salon FERME'
- alias: 'Alerte Pushbullet BAL Ouverte'
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: binary_sensor.door_window_sensor_158d000201e249
    to: 'on'
  action:
    service: notify.pushbullet_3t
    data:
      title: 'Appartement Terrasses'
      message: 'Courrier détecté'
