- alias: Harmony
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: input_select.harmony
    from: '-'
  action:
    - service: remote.turn_on
      entity_id: remote.hub_salon
      data_template:
        activity: >
          {% if is_state("input_select.harmony", "SHIELD") %}
            44273130
          {% elif is_state("input_select.harmony", "PC") %}
            44276908
          {% elif is_state("input_select.harmony", "Vinyle HIFI") %}
            44262776
          {% else %}
          {% endif %}
    - service: input_select.select_option
      entity_id: input_select.harmony
      data_template:
        option: "-"
- alias: Harmony Off
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: input_select.harmony
    to: 'Arrêt'
  action:
    - service: remote.turn_off
      entity_id: remote.hub_salon
    - service: input_boolean.turn_off
      entity_id: input_boolean.tvstate
    - service: input_select.select_option
      entity_id: input_select.harmony
      data_template:
        option: "-"
- alias: Harmony update TV boolean ON
  initial_state: 'on'
  trigger:
    platform: template
    value_template: "{% if is_state_attr('remote.hub_salon', 'current_activity', 'SHIELD') %}
                       true
                     {% elif is_state_attr('remote.hub_salon', 'current_activity', 'PC') %}
                       true 
                     {% else %}
                     {% endif %}"
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.tvstate
#- alias: Harmony Chromecast AllZoneStereoOFF
#  initial_state: 'on'
#  trigger:
#    platform: template
#    value_template: "{% if is_state_attr('remote.hub_salon', 'current_activity', 'TV') %}true{% endif %}"
#  action:
#    - service: switch.turn_off
#      entity_id: switch.allzonestereo
#- alias: Harmony Vinyle AllZoneStereo
#  initial_state: 'off'
#  trigger:
#    platform: state
#    entity_id: remote.hub_salon
#  condition:
#    condition: template
#    value_template: '{{ trigger.to_state.attributes.current_activity == "Vinyle Salon" }}'
#  action:
#    - service: switch.turn_on
#      entity_id: switch.allzonestereo
#- alias: Harmony Vinyle UnMuteFix
#  initial_state: 'off'
#  trigger:
#    platform: state
#    entity_id: remote.hub_salon
#  condition:
#    - condition: template
#      value_template: '{{ trigger.to_state.attributes.current_activity == "Vinyle Salon" }}'
#    - condition: template
#      value_template: '{{ trigger.from_state.attributes.current_activity == "TV" }}'
#  action:
#     - delay: 5
#     - service: remote.send_command
#       entity_id: remote.hub_salon
#       data:
#         device: "45999099"
#         command: "Mute"
#- alias : Harmony vinyle volume
#  initial_state: 'off'
#  trigger:
#    platform: state
#    entity_id: remote.hub_salon
#  condition:
#    - condition: template
#      value_template: '{{ trigger.to_state.attributes.current_activity == "Vinyle Salon" }}'
#  action:
#     - delay: 2
#     - service: media_player.volume_set
#       entity_id: media_player.denon_salon
#       data:
#         volume_level: 0.54
#- alias : Harmony shield tv volume
#  initial_state: 'on'
#  trigger:
#    platform: state
#    entity_id: remote.hub_salon
#  condition:
#    - condition: template
#      value_template: '{{ trigger.to_state.attributes.current_activity == "SHIELD TV" }}'
#    - condition: template
#      value_template: '{{ trigger.from_state.attributes.current_activity == "Vinyle Salon" }}'
#  action:
#     - service: media_player.volume_set
#       entity_id: media_player.denon_salon
#       data:
#         volume_level: 0.38
