- alias: 'Media KODI Baisser les lumières play'
  trigger:
    platform: state
    entity_id: media_player.junglekodi
    to: playing
  condition:
  - condition: state
    entity_id: device_tracker.jungle3t_wifi
    state: 'home'
  - condition: or
    conditions:
      - condition: template
        value_template: "{{ is_state_attr('media_player.junglekodi', 'media_content_type', 'tvshow') }}"
      - condition: template
        value_template: "{{ is_state_attr('media_player.junglekodi', 'media_content_type', 'movie') }}"
  action:
    service: scene.turn_on
    entity_id: scene.plexon
- alias: 'Media KODI Monter les lumières pause'
  trigger:
    platform: state
    entity_id: media_player.junglekodi
    to: paused
  condition:
  - condition: state
    entity_id: device_tracker.jungle3t_wifi
    state: 'home'
  - condition: or
    conditions:
      - condition: template
        value_template: "{{ is_state_attr('media_player.junglekodi', 'media_content_type', 'tvshow') }}"
      - condition: template
        value_template: "{{ is_state_attr('media_player.junglekodi', 'media_content_type', 'movie') }}"
  action:
    service: scene.turn_on
    entity_id: scene.plexpause
- alias: 'Media KODI Monter les lumières stop'
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: media_player.junglekodi
    to: idle
    for:
      hours: 00
      minutes: 00
      seconds: 03
  condition:
  - condition: state
    entity_id: device_tracker.jungle3t_wifi
    state: 'home'
  action:
    service: scene.turn_on
    entity_id: scene.plexoff
