- alias: TTS GoogleHome keupon arrive advanced
  initial_state: 'off'
  trigger:
    platform: state
    entity_id: binary_sensor.door_window_sensor_158d00019fd4b5
    to: 'on'
  condition: 
    condition: and
    conditions:
      - condition: state
        entity_id: device_tracker.keupon_huawei
        state: 'home'
      - condition: template
        value_template: '{{(as_timestamp(now())-as_timestamp(states.device_tracker.keupon_huawei.last_updated)) < 300 }}'
  action:
    - service: media_player.volume_set
      entity_id: media_player.junglehomemini
      data:
        volume_level: 0.3
    - service: media_player.play_media
      entity_id: media_player.junglehomemini
      data:
        media_content_id: !secret url_mp3_waza
        media_content_type: music
    - delay: 00:00:05
    - service: tts.google_say
      entity_id: media_player.junglehomemini
      data:
        message: 'Monsieur Keupon est dans la place !'
        language: 'fr'
- alias: TTS GoogleHome Basil arrive
  trigger:
    platform: state
    entity_id: device_tracker.basil_lg
    to: 'home'
  action:
    - service: media_player.volume_set
      entity_id: media_player.junglehomemini
      data:
        volume_level: 0.5
    - service: tts.google_say
      entity_id: media_player.junglehomemini
      data:
        message: 'Jinjeul, tu as de la visite, Basil est arrivé'
        language: 'fr'
- alias: TTS GoogleHome Nico arrive
  trigger:
    platform: state
    entity_id: device_tracker.nicolas_op5
    to: 'home'
  action:
    - service: media_player.volume_set
      entity_id: media_player.junglehomemini
      data:
        volume_level: 0.5
    - service: tts.google_say
      entity_id: media_player.junglehomemini
      data:
        message: 'Jinjeul, tu as de la visite, Nico est arrivé'
        language: 'fr'
- alias: TTS GoogleHome Manon arrive
  trigger:
    platform: state
    entity_id: device_tracker.manon_pocophonef1
    to: 'home'
  action:
    - service: media_player.volume_set
      entity_id: media_player.junglehomemini
      data:
        volume_level: 0.5
    - service: tts.google_say
      entity_id: media_player.junglehomemini
      data:
        message: 'Jinjeul, tu as de la visite, Manon est arrivé'
        language: 'fr'
- alias: TTS GoogleHome Bertrand arrive
  trigger:
    platform: state
    entity_id: device_tracker.bertrand_op6t
    to: 'home'
  action:
    - service: media_player.volume_set
      entity_id: media_player.junglehomemini
      data:
        volume_level: 0.5
    - service: tts.google_say
      entity_id: media_player.junglehomemini
      data:
        message: 'Jinjeul, tu as de la visite, Bertrand est arrivé'
        language: 'fr'
- alias: TTS GoogleHome Loic arrive
  trigger:
    platform: state
    entity_id: device_tracker.loic_galaxys8
    to: 'home'
  action:
    - service: media_player.volume_set
      entity_id: media_player.junglehomemini
      data:
        volume_level: 0.5
    - service: tts.google_say
      entity_id: media_player.junglehomemini
      data:
        message: 'Jinjeul, tu as de la visite, Loulou est arrivé'
        language: 'fr'
- alias: TTS GoogleHome Keupon arrive
  trigger:
    platform: state
    entity_id: device_tracker.keupon_huawei
    to: 'home'
  action:
    - service: media_player.volume_set
      entity_id: media_player.junglehomemini
      data:
        volume_level: 0.5
    - service: tts.google_say
      entity_id: media_player.junglehomemini
      data:
        message: 'Jinjeul, tu as de la visite, Keupon est arrivé'
        language: 'fr'
