- alias: 'EDF - Calcul cout journalier'
  initial_state: 'on'
  trigger:
    - platform: time
      minutes: '/1'
      seconds: 0
  action:
    - service: mqtt.publish
      data:
        retain: 'true'
        topic: 'jungle/edf/cout_today'
        payload_template: >-
          {% if is_state('binary_sensor.hp_edf', 'on') %}
            {{states.sensor.cout_journalier.state | float + ( states.sensor.releve_consommation_esp.state | float / 1000 * 0.1466)}}
          {% else %}
            {{states.sensor.cout_journalier.state | float + ( states.sensor.releve_consommation_esp.state | float / 1000 * 0.1200)}}
          {% endif %}
    - service: mqtt.publish
      data:
        retain: 'true'
        topic: 'jungle/edf/conso_today'
        payload_template: '{{(states.sensor.conso_journaliere.state | float + states.sensor.releve_consommation_esp.state | float) | round (0) }}'
- alias: 'EDF - Remise à zero journalier'
  initial_state: 'on'
  trigger:
    - platform: time
      hours: 0
      minutes: 0
      seconds: 0
  action:
    - service: mqtt.publish
      data:
        retain: 'true'
        topic: 'jungle/edf/cout_today'
        payload: '0'
    - service: mqtt.publish
      data:
        retain: 'true'
        topic: 'jungle/edf/conso_today'
        payload: '0'