- alias: 'Reveil - chambre - Matin semaine'
  initial_state: 'on'
  trigger:
    - platform: time
      minutes: '/1'
      seconds: 0
  condition:
    - condition: state
      entity_id: device_tracker.jungle3t_wifi
      state: 'home'
    - condition: state
      entity_id: input_boolean.alarmweeknoisy
      state: 'off'
    - condition: state
      entity_id: input_boolean.alarmweekon
      state: 'on'
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
    - condition: template
      value_template: '{{ now().strftime("%H:%M") == states.sensor.alarm_time.state }}'
  action:
    - service: scene.turn_on
      entity_id: scene.chambre_on
    - service: homeassistant.turn_on
      entity_id: light.salon, light.cuisine, light.vestibule, light.salledebain, light.gateway_light_34ce008db5a7, light.tv_strip
- alias: 'Reveil - chambre - Sonore Matin semaine'
  initial_state: 'on'
  trigger:
    - platform: time
      minutes: '/1'
      seconds: 0
  condition:
    - condition: state
      entity_id: device_tracker.jungle3t_wifi
      state: 'home'
    - condition: state
      entity_id: input_boolean.alarmweeknoisy
      state: 'on'
    - condition: state
      entity_id: input_boolean.alarmweekon
      state: 'on'
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
    - condition: template
      value_template: '{{ now().strftime("%H:%M") == states.sensor.alarm_time.state }}'
  action:
    - service: remote.send_command
      entity_id: remote.hub_salon
      data:
        device: "45999099"
        command: "InputMediaPlayer"
    - service: media_player.turn_on
      entity_id: media_player.la_tele
    - service: media_player.volume_set
      entity_id: media_player.junglehomemini
      data:
        volume_level: 0.30
    - delay: 2
    - service: media_player.volume_set
      entity_id: media_player.la_tele
      data:
        volume_level: 0.15
    - service: media_player.play_media
      entity_id: media_player.la_tele
      data_template:
        media_content_id: 'http://108.163.197.114:8141/;stream.mp3'
        media_content_type: music
    - service: tts.google_say
      entity_id: media_player.junglehomemini
      data_template:
        message: "Salut Mikou, il est {{now().hour}} heure {{now().minute}}. Il est l'heure de se bouger le cul, voici un peu de ragga-d'jeunegueule pour te motiver ! Il fera {{states.sensor.pws_temp_high_avg_c.state}} degrés aujourd'hui passes une bonne journée !"
        cache: false
        language: fr
    - service: scene.turn_on
      entity_id: scene.chambre_on
    - service: homeassistant.turn_on
      entity_id: light.salon, light.cuisine, light.vestibule, light.salledebain, light.gateway_light_34ce008db5a7, light.tv_strip
    - service: media_player.volume_set
      entity_id: media_player.la_tele
      data:
        volume_level: 0.25
    - delay: 20
    - service: media_player.volume_set
      entity_id: media_player.la_tele
      data:
        volume_level: 0.30
    - delay: 100
    - service: media_player.volume_set
      entity_id: media_player.la_tele
      data:
        volume_level: 0.40
- alias: 'Réveil - Send Tasker Event'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: input_number.alarmhour,input_number.alarmminutes,input_boolean.alarmweekon
  condition:
    - condition: state
      entity_id: device_tracker.jungle3t_wifi
      state: 'home'
  action:
    - service: shell_command.taskerevent
