- alias: 'Media androidtv Baisser les lumières play'
  trigger:
    platform: state
    entity_id: media_player.jungleshield
    to: playing
  condition:
  - condition: state
    entity_id: device_tracker.jungle3t_wifi
    state: 'home'
  - condition: or
    conditions:
      - condition: template
        value_template: "{{ is_state_attr('media_player.jungleshield', 'app_name', 'Netflix') }}"
      - condition: template
        value_template: "{{ is_state_attr('media_player.jungleshield', 'app_name', 'PrimeVideo') }}"
  action:
    service: scene.turn_on
    entity_id: scene.plexon
- alias: 'Media androidtv Monter les lumières pause'
  trigger:
    platform: state
    entity_id: media_player.jungleshield
    to: paused
  condition:
  - condition: state
    entity_id: device_tracker.jungle3t_wifi
    state: 'home'
  - condition: or
    conditions:
      - condition: template
        value_template: "{{ is_state_attr('media_player.jungleshield', 'app_name', 'Netflix') }}"
      - condition: template
        value_template: "{{ is_state_attr('media_player.jungleshield', 'app_name', 'PrimeVideo') }}"
  action:
    service: scene.turn_on
    entity_id: scene.plexpause
- alias: 'Media androidtv Monter les lumières stop'
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: media_player.jungleshield
    to: idle
    for:
      hours: 00
      minutes: 00
      seconds: 03
  condition:
  - condition: state
    entity_id: device_tracker.jungle3t_wifi
    state: 'home'
  action:
    service: scene.turn_on
    entity_id: scene.plexoff
