- alias: 'Media Salon harmony vinyle single jungletap_vinyle'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.switch_158d000120d6d0
      click_type: single
  action:
    - service: switch.turn_on
      entity_id: switch.harmony_vinyle