- alias: 'Media Salon harmony vinyle single jungletap_vinyle'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.switch_158d000120d6d0
      click_type: single
  action:
    - service: switch.turn_on
      entity_id: switch.harmony_vinyle
- alias: 'Media Salon harmony TV single jungletap_tv'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.switch_158d00029300a8
      click_type: single
  action:
    - service: switch.turn_on
      entity_id: switch.harmony_shield_tv
- alias: 'Media Salon harmony PC longpress jungletap_tv'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.switch_158d00029300a8
      click_type: long_click_press
  action:
    - service: switch.turn_on
      entity_id: switch.harmony_pc
- alias: 'Media Salon harmony Vinyle doubleclick jungletap_tv'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.switch_158d00029300a8
      click_type: double
  action:
    - service: switch.turn_on
      entity_id: switch.harmony_vinyle