- alias: 'Lumières Chambre On long jungletap'
  initial_state: 'off'
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.switch_158d00016bdb71
      click_type: long
  action:
    service: light.turn_off
    entity_id: light.chambre  