- alias: 'Media - PLEX - Baisser les lumières play'
  trigger:
    platform: state
    entity_id: sensor.plex_chromecast_status
    to: playing
  condition:
  - condition: state
    entity_id: sensor.chromecast_source
    state: 'Plex'
  - condition: state
    entity_id: device_tracker.jungle3t_wifi
    state: 'home'
  action:
    service: scene.turn_on
    entity_id: scene.plexon
- alias: 'Media - PLEX - Monter les lumières pause'
  trigger:
    platform: state
    entity_id: sensor.plex_chromecast_status
    to: paused
  condition:
  - condition: state
    entity_id: sensor.chromecast_source
    state: 'Plex'
  - condition: state
    entity_id: device_tracker.jungle3t_wifi
    state: 'home'
  action:
    service: scene.turn_on
    entity_id: scene.plexpause
- alias: 'Media - PLEX - Monter les lumières stop'
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: sensor.plex_chromecast_status
    to: idle
    for:
      hours: 00
      minutes: 00
      seconds: 03
  condition:
  - condition: state
    entity_id: device_tracker.jungle3t_wifi
    state: 'home'
  action:
    service: scene.turn_on
    entity_id: scene.plexoff
