- alias: 'Media PLEX Baisser les lumières play'
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: sensor.shieldplex_state
      to: playing
    - platform: state
      entity_id: sensor.shieldplex_state
      to: resumed
  condition:
  - condition: state
    entity_id: device_tracker.jungle3t_wifi
    state: 'home'
  action:
    service: scene.turn_on
    entity_id: scene.plexon
- alias: 'Media PLEX Monter les lumières pause'
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: sensor.shieldplex_state
    to: paused
  condition:
  - condition: state
    entity_id: device_tracker.jungle3t_wifi
    state: 'home'
  action:
    service: scene.turn_on
    entity_id: scene.plexpause
- alias: 'Media PLEX Monter les lumières stop'
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: sensor.shieldplex_state
    to: stopped
    for:
      hours: 00
      minutes: 00
      seconds: 01
  condition:
  - condition: state
    entity_id: device_tracker.jungle3t_wifi
    state: 'home'
  action:
    service: scene.turn_on
    entity_id: scene.plexoff
