sensor:
  - platform: mqtt  
    state_topic: "jungle/sensornode3"  
    name: "Humidite 3"  
    unit_of_measurement: "%"  
    value_template: '{{ value_json.humidity | round(1) }}' 
  - platform: mqtt  
    state_topic: "jungle/sensornode3"  
    name: "Temperature 3"  
    unit_of_measurement: "°F"
    value_template: '{{ value_json.temperature | round(1) }}'
  - platform: mqtt
    state_topic: "jungle/sensornode3"
    name: "Real Feel 3"
    unit_of_measurement: "°F"
    value_template: '{{ value_json.heatIndex | round(1) }}'
group:
  sensor_node_3_card:
    name: Chambre
    entities:
      - sensor.temperature_3
      - sensor.humidite_3
switch:
  - platform: mqtt
    name: "Radiateur Chambre"  
    state_topic: "jungle/radcontrol/chambre/state"
    command_topic: "jungle/radcontrol/chambre/set"
    payload_on: "1"
    payload_off: "0"  
    qos: 0
    optimistic: false
light:
  - platform: yeelight
    devices:
      192.168.1.172:
        name: Chambre
automation:
  - alias: 'Chauffage - Chambre - thermostat 20 à 06h00 semaine'
    initial_state: 'on'
    trigger:
      platform: time
      hours: 06
      minutes: 0
      seconds: 0
    condition:
      - condition: state
        entity_id: device_tracker.jungle3t_wifi
        state: 'home'
      - condition: time
        weekday:
          - mon
          - tue
          - wed
          - thu
          - fri
    action:
      - service: climate.set_temperature
        data:
          entity_id: climate.chambre
          temperature: '20'
  - alias: 'Chauffage - Chambre - thermostat 17 à 08h00 semaine'
    initial_state: 'on'
    trigger:
      platform: time
      hours: 08
      minutes: 0
      seconds: 0
    condition:
      - condition: time
        weekday:
          - mon
          - tue
          - wed
          - thu
          - fri
    action:
      - service: climate.set_temperature
        data:
          entity_id: climate.chambre
          temperature: '17'
  - alias: 'Chauffage - Chambre - 17 Départ Appart'
    initial_state: 'on'
    trigger:
      platform: state
      entity_id: device_tracker.jungle3t_wifi
      to: 'not_home'
    action:
      - service: climate.set_temperature
        data:
          entity_id: climate.chambre
          temperature: '17'
      - service : homeassistant.turn_off
        data:
          entity_id: switch.radiateur_chambre