####################################################################################
#                                                                                  #
#                                                                                  #
#                                MAIN COMPONENTS                                   #
#                                                                                  #
#                                                                                  #
####################################################################################

light:
  - platform: lifx

device_tracker:
  - platform: ddwrt
    host: !secret ddwrt_ip
    username: admin 
    password: !secret router_password
  - platform: gpslogger
  - platform: owntracks
    max_gps_accuracy: 200

scene:
  - platform: lifx_cloud
    token: !secret lifxapitoken

ifttt:
  key: !secret ifttt_webhooks_key
sensor:
  - platform: haveibeenpwned
    email: 
      - !secret email_1
      - !secret email_2
  - platform: mqtt_room
    device_id: !secret junglenut_id
    name: 'JungleNUT'
    state_topic: 'room_presence'
    timeout: 5
    away_timeout: 60
  - platform: worldclock
    time_zone: Europe/Paris
    name: France
  - platform: worldclock
    time_zone: Europe/Helsinki
    name: Finlande
  - platform: worldclock
    time_zone: Europe/Istanbul
    name: Turquie
weather:
  - platform: yweather

####################################################################################
#                                                                                  #
#                                                                                  #
#                                THERMOSTAT                                        #
#                                                                                  #
#                                                                                  #
####################################################################################

climate:
  - platform: generic_thermostat
    name: Salon
    heater: switch.radiateur_salon
    target_sensor: sensor.temperature_1
    min_temp: 17
    max_temp: 24
    target_temp: 18
    tolerance: 0.5
    min_cycle_duration:
      seconds: 5
    keep_alive:
      minutes: 5
  - platform: generic_thermostat
    name: Chambre
    heater: switch.radiateur_chambre
    target_sensor: sensor.temperature_3
    target_temp: 17
    min_temp: 17
    max_temp: 24
    tolerance: 0.5
    min_cycle_duration:
      seconds: 5
    keep_alive:
      minutes: 5