xiaomi_aqara:
  discovery_retry: 5
  gateways:
    - key: !secret xiaomi_gateway_key
automation:
  - alias: 'Lumières - Appartement - ON Arrivée Appart'
    initial_state: 'on'
    trigger:
      platform: state
      entity_id: device_tracker.jungle3t_wifi
      to: 'home'
    condition:
      condition: numeric_state
      entity_id: sensor.lumsens_1
      below: '300'
    action:
      service: homeassistant.turn_on
      entity_id: light.salon, light.cuisine

  - alias: 'Lumières - Appartement - OFF au Départ'
    initial_state: 'on'
    trigger:
      platform: state
      entity_id: device_tracker.jungle3t_wifi
      to: 'not_home'
      # AJOUTER UN TRIGGER SI LAST MOTION ENTREE MOINS DE 2 MINUTE
    action:
      service: light.turn_off
      entity_id: group.all_lights

  - alias: 'Mediaplayer - Appartement - OFF au Départ'
    initial_state: 'on'
    trigger:
      platform: state
      entity_id: device_tracker.jungle3t_wifi
      to: 'not_home'
      # AJOUTER UN TRIGGER SI LAST MOTION ENTREE MOINS DE 2 MINUTE
    action:
      - service: media_player.turn_off
        entity_id: group.mediaplayers
      - service: automation.trigger
        entity_id: automation.harmony_off
      - service: switch.turn_off
        entity_id: switch.jungle_pc
  - alias: 'Lumières - Appartement - OFF on single jungletap'
    trigger:
      platform: event
      event_type: click
      event_data:
        entity_id: binary_sensor.switch_158d00016bdb71
        click_type: single
    action:
      service: light.turn_off
      entity_id: group.all_lights
  - alias: 'Lumières - Appartement - ON on double jungletap'
    trigger:
      platform: event
      event_type: click
      event_data:
        entity_id: binary_sensor.switch_158d00016bdb71
        click_type: double
    action:
      service: homeassistant.turn_on
      entity_id: light.salon, light.cuisine, light.vestibule, light.salledebain, light.chambre
  - alias: 'Lumières - Appartement - Chambre bluetooth on long jungletap'
    trigger:
      platform: event
      event_type: click
      event_data:
        entity_id: binary_sensor.switch_158d00016bdb71
        click_type: long_click_press
    action:
      - service: remote.turn_on
        entity_id: remote.hub_salon
        data_template:
          activity: 28429925
  - alias: 'Lumières - Salon - Toggle light on leftswitch'
    trigger:
      platform: event
      event_type: click
      event_data:
        entity_id: binary_sensor.wall_switch_left_158d000163a561
        click_type: single
    action:
      service: homeassistant.toggle
      entity_id: light.salon, light.cuisine
  - alias: 'Lumières - Chambre - Toggle light on rightswitch'
    trigger:
      platform: event
      event_type: click
      event_data:
        entity_id: binary_sensor.wall_switch_right_158d000163a561
        click_type: single
    action:
      service: homeassistant.toggle
      entity_id: light.chambre