sun:
mqtt:  
  broker: localhost
  port: 1883
  username: !secret mqtt_login_junglenas
  password: !secret mqtt_password_junglenas
device_tracker:
  - platform: ddwrt
    host: !secret ddwrt_ip
    username: admin 
    password: !secret router_password
    interval_seconds: 10
    new_device_defaults:
      track_new_devices: False
      hide_if_away: False
  - platform: googlehome
    host: !secret ip_google_home
ifttt:
  key: !secret ifttt_webhooks_key
sensor:
  - platform: command_line
    name: "Download Grafana - temps"
    command: !secret cmd_get_grafana_conso
  - platform: command_line
    name: "Download Grafana - conso"
    command: !secret cmd_get_grafana_temp
  - platform: haveibeenpwned
    email: 
      - !secret email_1
      - !secret email_2
  - platform: mqtt_room
    device_id: !secret junglenut_id
    state_topic: "room_presence"
    name: 'JungleNUT'
    timeout: 5
    away_timeout: 60
  - platform: worldclock
    time_zone: Europe/Paris
    name: France
  - platform: worldclock
    time_zone: Europe/Helsinki
    name: Finlande
  - platform: worldclock
    time_zone: Europe/Istanbul
    name: Turquie
  - platform: cpuspeed
  - platform: imap
    name: GMail IMAP
    server: !secret mail_server
    port: 993
    username: !secret gmail_user
    password: !secret gmail_pass
    folder: inbox
  - platform: yr
    monitored_conditions:
      - symbol
      - temperature
      - precipitation
      - windSpeed
      - windDirection
      - humidity
      - cloudiness
  - platform: moon
  - platform: time_date
    display_options:
      - 'time'
      - 'date'
  - platform: history_stats
    name: Radiateur Chambre ON today
    entity_id: switch.radiateur_chambre
    state: 'on'
    type: time
    start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
    end: '{{ now() }}'
  - platform: history_stats
    name: Radiateur lit ON today
    entity_id: switch.sonoff_bed
    state: 'on'
    type: time
    start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
    end: '{{ now() }}'
  - platform: history_stats
    name: Radiateur Salon ON today
    entity_id: switch.radiateur_salon
    state: 'on'
    type: time
    start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
    end: '{{ now() }}'
  - platform: template
    sensors:
      radiateur_chambre_on_today_view:
        unit_of_measurement: 'Heures'
        value_template: '{{ states.sensor.radiateur_chambre_on_today.state }}'
      radiateur_lit_on_today_view:
        unit_of_measurement: 'Heures'
        value_template: '{{ states.sensor.radiateur_lit_on_today.state }}'
      radiateur_salon_on_today_view:
        unit_of_measurement: 'Heures'
        value_template: '{{ states.sensor.radiateur_salon_on_today.state }}'
  - platform: meteo_france
    postal_code: !secret postal_code
    monitored_conditions:
      - temperature
      - weather
      - wind_speed
      - uv
      - next_rain
      - freeze_chance
      - rain_chance
      - snow_chance
      - thunder_chance 
xiaomi_aqara:
  discovery_retry: 5
  gateways:
    - mac: !secret xiaomi_gateway_mac
      key: !secret xiaomi_gateway_key
      host: !secret xiaomi_gateway_ip
notify:
  - name: pushbullet_3t
    platform: pushbullet
    api_key: !secret pushbullet_api
  - name: gmail_smtp
    platform: smtp
    server: smtp.gmail.com
    port: 587
    timeout: 15
    sender: !secret gmail_user
    starttls: 1
    username: !secret gmail_user
    password: !secret gmail_pass
    recipient: !secret gmail_user
tts:
  - platform: google
    cache: true
    cache_dir: /tmp/tts
    time_memory: 300
binary_sensor:
  - platform: trend
    sensors:
      gmail_new:
        entity_id: sensor.gmail_imap
switch:
  - platform: command_line
    switches:
      portail:
       command_on: !secret portail_trigger
       command_off: !secret portail_trigger
       friendly_name: Portail des terrasses
scene:
  - platform: lifx_cloud
    token: !secret lifxapitoken
  - name: plexon
    entities:
        light.salon:
          state: on
          color_temp: 333
          brightness: 12
          transition: 10
        light.tv_strip:
          state: on
          brightness: 3
          transition: 20
          rgb_color: [128, 147, 255]
        light.cuisine:
          state: off
          transition: 10
        switch.lumiere_bureau:
          state: off
        light.gateway_light_34ce008db5a7:
          state: on
          brightness: 20
          transition: 20
        light.vestibule:
          state: off
          transition: 30
  - name: plexoff
    entities:
        light.salon:
          state: on
          color_temp: 333
          brightness: 250
          transition: 30
        light.gateway_light_34ce008db5a7:
          state: on
          brightness: 240
          transition: 20
        light.tv_strip:
          state: on
          brightness: 240
          transition: 10
          rgb_color: [64, 0, 255]
  - name: plexpause
    entities:
        light.salon:
          state: on
          color_temp: 333
          brightness: 131
          transition: 7
        light.gateway_light_34ce008db5a7:
          state: on
          brightness: 150
        light.vestibule:
          state: on
          transition: 5
  - name: cuisineoff
    entities:
        light.cuisine:
          state: off
          transition: 10
  - name: vestibuleoff
    entities:
        light.vestibule:
          state: off
          transition: 10
  - name: chambre_on
    entities:
        light.chambre:
          state: on
          transition: 60
history_graph:
  temperature_appartement:
    name: Température Appartement
    entities:
      - sensor.temperature_158d0001f52004
      - sensor.temperature_158d0001fa768f
      - sensor.temperature_158d0002273c15
    hours_to_show: 168
    refresh: 120
influxdb:
  host: localhost
  include:
    entities:
      - sensor.temperature_158d0001f52004
      - sensor.temperature_158d0001fa768f
      - sensor.temperature_158d0002273c15
      - sensor.releve_consommation_wh
google_assistant:
  project_id: !secret gassist_project_id
  exposed_domains:
    - switch
    - light
    - cover
  entity_config:
    switch.radiateur_chambre:
      expose: false
    switch.radiateur_salon:
      expose: false
    switch.sonoff_bed:
      name: lit
    switch.tv:
      expose: false
    light.yeelight_rgb_34ce0082379e:
      expose: false
    light.yeelight_rgb_34ce008cff26:
      expose: false
    light.yeelight_strip_7811dc672f73:
      expose: false
    light.yeelight_white_34ce008876d6:
      expose: false
    cover.volet_du_salon:
      name: Volet
camera:
  - platform: local_file
    name: Grafana_temperature
    file_path: !secret  grafana_path_temp
  - platform: local_file
    name: Grafana_conso
    file_path: !secret  grafana_path_conso