####################################################################################
#                                                                                  #
#                                                                                  #
#                                MAIN COMPONENTS                                   #
#                                                                                  #
#                                                                                  #
####################################################################################

light:
  - platform: lifx

device_tracker:
  - platform: ddwrt
    host: 192.168.1.1
    username: admin 
    password: !secret router_password
  - platform: gpslogger
  - platform: owntracks
    max_gps_accuracy: 200

scene:
  - platform: lifx_cloud
    token: !secret lifxapitoken

ifttt:
  key: !secret ifttt_webhooks_key
sensor:
  - platform: haveibeenpwned
    email: 
      - mikael.boulo@gmail.com
      - contact@jungleman.fr
  - platform: mqtt_room
    device_id: d7b08f66e830
    name: 'JungleNUT'
    state_topic: 'room_presence'
    timeout: 5
    away_timeout: 60
weather:
  - platform: yweather

    
# Performance Issue with Bluetooth LE tracker : using room-assistant instead with MQTT
#  - platform: bluetooth_le_tracker
#zwave:
#  usb_path: /dev/zwave

####################################################################################
#                                                                                  #
#                                                                                  #
#                                THERMOSTAT                                        #
#                                                                                  #
#                                                                                  #
####################################################################################

climate:
#Thermostat Salon
  - platform: generic_thermostat
    name: Salon
    heater: switch.radiateur_salon
    target_sensor: sensor.temperature_1
    min_temp: 17
    max_temp: 24
    target_temp: 18
    tolerance: 0.5
    min_cycle_duration:
      seconds: 5
    keep_alive:
      minutes: 5
#Thermostat Chambre
  - platform: generic_thermostat
    name: Chambre
    heater: switch.radiateur_chambre
    target_sensor: sensor.temperature_3
    target_temp: 17
    min_temp: 16
    max_temp: 20
    tolerance: 0.5
    min_cycle_duration:
      seconds: 5
    keep_alive:
      minutes: 5