sun:
yeelight:
    devices:
      192.168.1.170:
        name: Vestibule
      192.168.1.171:
        name: Salledebain
      192.168.1.172:
        name: Chambre
      192.168.1.173:
        name: Vinyles Strip
      192.168.1.174:
        name: Bureau Strip
mqtt:  
  broker: localhost
  port: 1883
  username: !secret mqtt_login_junglenas
  password: !secret mqtt_password_junglenas
device_tracker:
  - platform: ddwrt
    host: !secret ddwrt_ip
    username: admin 
    password: !secret router_password
    interval_seconds: 10
    new_device_defaults:
      track_new_devices: False
sensor:
  - platform: command_line
    name: "Download Grafana - temps"
    command: !secret cmd_get_grafana_conso
  - platform: command_line
    name: "Download Grafana - conso"
    command: !secret cmd_get_grafana_temp
#  - platform: mqtt_room
#    device_id: !secret junglenut_id
#    state_topic: "room_presence"
#    name: 'JungleNUT'
#    timeout: 5
#    away_timeout: 60
  - platform: worldclock
    time_zone: Europe/Paris
    name: France
  - platform: worldclock
    time_zone: Europe/Helsinki
    name: Finlande
  - platform: worldclock
    time_zone: Europe/Istanbul
    name: Turquie
  - platform: cpuspeed
  - platform: yr
    monitored_conditions:
      - symbol
      - temperature
      - precipitation
      - windSpeed
      - windDirection
      - humidity
      - cloudiness
  - platform: moon
  - platform: time_date
    display_options:
      - 'time'
      - 'date'
  - platform: history_stats
    name: Radiateur Chambre ON today
    entity_id: switch.radiateur_chambre
    state: 'on'
    type: time
    start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
    end: '{{ now() }}'
  - platform: history_stats
    name: Radiateur lit ON today
    entity_id: switch.sonoff_bed
    state: 'on'
    type: time
    start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
    end: '{{ now() }}'
  - platform: history_stats
    name: Radiateur Salon ON today
    entity_id: switch.radiateur_salon
    state: 'on'
    type: time
    start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
    end: '{{ now() }}'
  - platform: template
    sensors:
      radiateur_chambre_on_today_view:
        unit_of_measurement: 'Heures'
        value_template: '{{ states.sensor.radiateur_chambre_on_today.state }}'
      radiateur_lit_on_today_view:
        unit_of_measurement: 'Heures'
        value_template: '{{ states.sensor.radiateur_lit_on_today.state }}'
      radiateur_salon_on_today_view:
        unit_of_measurement: 'Heures'
        value_template: '{{ states.sensor.radiateur_salon_on_today.state }}' 
switch:
  - platform: command_line
    switches:
      portail:
       command_on: !secret portail_trigger
       command_off: !secret portail_trigger
       friendly_name: Portail des terrasses
scene:
  - platform: lifx_cloud
    token: !secret lifxapitoken
script:
  scene_chambre_on:
    sequence:
      - service: light.turn_on
        data:
          entity_id: light.chambre
          transition: 60
  scene_cuisine_off:
    sequence:
      - service: light.turn_off
        data:
          entity_id: light.cuisine_2
          transition: 10
  scene_vestibule_off:
    sequence:
      - service: light.turn_off
        data:
          entity_id: light.vestibule
          transition: 10
influxdb:
  host: localhost
camera:
  - platform: local_file
    name: Grafana_temperature
    file_path: !secret  grafana_path_temp
  - platform: local_file
    name: Grafana_conso
    file_path: !secret  grafana_path_conso
meteo_france:
  - city: !secret city_name
#nextcloud:
#  - url: !secret nextcloud_url
#    username: !secret nextcloud_username
#    password: !secret nextcloud_password
notify:
- name: gotify_1
  platform: rest
  resource: !secret gotify_url
  method: POST_JSON
  headers: 
    X-Gotify-Key: !secret gotify_key
  message_param_name: message
  title_param_name: title
