sensor:
  - platform: template
    sensors:
      alarm_time:
        friendly_name: 'Time'
        value_template: '{{ "%0.02d:%0.02d" | format(states("input_number.alarmhour") | int, states("input_number.alarmminutes") | int) }}'
input_number:
  alarmhour:
    name: Heure
    icon: mdi:timer
    initial: 8
    min: 0
    max: 23
    step: 1
  alarmminutes:
    name: Minutes
    icon: mdi:timer
    initial: 0
    min: 0
    max: 59
    step: 5
input_boolean:
  alarmweekon:
    icon: mdi:alarm
    name: Activé
    initial: on
  alarmweeknoisy:
    icon: mdi:speaker
    name: "Musique dans le salon ?"
    initial: off
#shell_command:
#  taskerevent: !secret url_tasker_alarmclock