remote:
  - platform: harmony
    name: 'HUB Salon'
    host: !secret harmony_ip
    port: !secret harmony_port
    activity: 'Chromecast'
media_player:
  - platform: denonavr
    host: !secret denon_ip
    name: Denon Salon
    show_all_sources: False
    zones:
      - zone: Zone2
        name: Denon Bureau
shell_command:
  junglepc_shutdown: !secret junglepc_shutdown
  junglepc_restart: !secret junglepc_restart
  junglepc_sleep: !secret junglepc_sleep
  junglenas_killit: !secret junglenas_poweroff
  junglenas_powerback: !secret junglenas_poweron
  433_ouvrir_portail: !secret portail_ouvrir
switch:
  - platform: wake_on_lan
    mac: !secret junglepc_mac
    name: "Jungle PC"
    host: !secret junglepc_ip
    turn_off:
      service: shell_command.junglepc_shutdown
  - platform: template
    switches:
      tv:
        friendly_name: 'Télé Philips'
        value_template: "{{ is_state('input_boolean.tvstate', 'on')}}"
        turn_on:
          service: script.turn_on
          entity_id: script.philipstv_on
        turn_off:
          service: script.turn_on
          entity_id: script.philipstv_off
      allzonestereo:
        friendly_name: 'Toutes Zones Stereo'
        value_template: "{{ is_state('input_boolean.allzonestereostate', 'on')}}"
        turn_on:
          service: script.turn_on
          entity_id: script.allzonestereo_on
        turn_off:
          service: script.turn_on
          entity_id: script.allzonestereo_off
      mute_denon_salon:
        friendly_name: 'Mute Denon Salon'
        value_template: "{{ state_attr('media_player.denon_salon', 'is_volume_muted') }}"
        turn_on:
          service: script.turn_on
          entity_id: script.mutedenonsalon_onoff
        turn_off:
          service: script.turn_on
          entity_id: script.mutedenonsalon_onoff
      mcs_denon_salon:
        friendly_name: 'MultiChannelStereo Denon Salon'
        value_template: "{{ is_state('input_boolean.mcs_denon_salon', 'on')}}"
        turn_on:
          service: script.turn_on
          entity_id: script.mcsdenonsalon_onoff
        turn_off:
          service: script.turn_on
          entity_id: script.mcsdenonsalon_onoff
      harmony_shield_tv:
        friendly_name: 'Activité SHIELD TV'
        value_template: "{{ is_state_attr('media_player.denon_salon', 'source', 'SHIELD') }}"
        turn_on:
          service: script.turn_on
          entity_id: script.harmony_shield_tv_onoff
        turn_off:
          service: script.turn_on
          entity_id: script.harmony_shield_tv_onoff
      harmony_vinyle:
        friendly_name: 'Activité Vinyle'
        value_template: "{{ is_state_attr('media_player.denon_salon', 'source', 'Vinyle') }}"
        turn_on:
          service: script.turn_on
          entity_id: script.harmony_vinyle_onoff
        turn_off:
          service: script.turn_on
          entity_id: script.harmony_vinyle_onoff
      harmony_off:
        friendly_name: 'Arrêter Activité Harmony'
        value_template: "{{ is_state_attr('remote.hub_salon', 'current_activity', 'PowerOff') }}"
        turn_on:
          service: script.turn_on
          entity_id: script.harmony_off
        turn_off:
          service: script.turn_on
          entity_id: script.harmony_off
      harmony_pc:
        friendly_name: 'Activité PC'
        value_template: "{{ is_state_attr('media_player.denon_salon', 'source', 'PC') }}"
        turn_on:
          service: script.turn_on
          entity_id: script.harmony_pc_onoff
        turn_off:
          service: script.turn_on
          entity_id: script.harmony_pc_onoff
sensor:
  - platform: deluge
    host: !secret junglenas_ip
    username: !secret deluge_user
    password: !secret deluge_pass
    monitored_variables:
      - 'current_status'
      - 'download_speed'
      - 'upload_speed'
  - platform: sonarr
    api_key: !secret sonarr_api
    host: !secret junglenas_ip
    monitored_conditions:
      - upcoming
      - diskspace
      - wanted
      - queue
    days: 2
    include_paths: !secret sonarr_series_path
  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /home
      - type: memory_free
      - type: processor_use
      - type: ipv4_address
        arg: eth0
  - platform: tautulli
    api_key: !secret TAUTULLI_API_KEY
    host: !secret TAUTULLI_HOST
    monitored_users:
      - !secret tautulli_user_1
    monitored_conditions:
      - quality_profile
      - bitrate
      - bandwidth
      - file
      - video_decision
      - stream_audio_decision
      - transcode_decision
      - full_title
      - library_name
      - media_type
      - state
      - player
  - platform: mqtt
    name: shieldplex_state
    state_topic: !secret topic_shieldplexstate
    value_template: '{{ value_json.body }}'
input_boolean:
  tvstate:
    name: 'Etat du téléviseur'
    initial: off
    icon: mdi:television-classic
  allzonestereostate:
    name: 'All Zone ON/OFF'
    initial: off
    icon: mdi:speaker
  mcs_denon_salon:
    name: 'MultiChannelStereo Denon'
    initial: off
    icon: mdi:speaker
  vacancesstate:
    name: 'Mode Vacances'
    initial: off
    icon: mdi:airplane-takeoff
input_select:
  pcoptions:
    name: 'Actions'
    options:
      - Choisir une action
      - Eteindre
      - Redémarrer
      - Veille
    initial: Choisir une action
    icon: mdi:desktop-tower
  harmony:   
    name: Mettre une activité
    options:
      - Choisir la source
      - Arrêt
      - TV
      - PC
      - Vinyle Salon
      - Bluetooth Bureau
      - Vinyle Bureau
      - PC Musique Bureau
      - Google Home AVR BT
    initial: Choisir la source
    icon: mdi:monitor
script:
  philipstv_on:
    sequence:
      - service: input_boolean.turn_on
        entity_id: input_boolean.tvstate
      - service: remote.send_command
        entity_id: remote.hub_salon
        data:
          device: "61872874"
          command: "PowerOn"
  philipstv_off:
    sequence:
      - service: input_boolean.turn_off
        entity_id: input_boolean.tvstate
      - service: script.turn_on
        entity_id: script.65oled803_12_3_off
      - delay: 5
      - service: remote.send_command
        entity_id: remote.hub_salon
        data:
          device: "61872874"
          command: "PowerOff"
  65oled803_12_3_off:
    sequence:
      - condition: template
        value_template: '{{ states.remote.hub_salon.attributes.current_activity == "TV" }}'
      - service: remote.turn_off
        entity_id: remote.hub_salon
  allzonestereo_on:
    sequence:
      - service: input_boolean.turn_on
        entity_id: input_boolean.allzonestereostate
      - service: remote.send_command
        entity_id: remote.hub_salon
        data:
          device: "45999099"
          command: "AllZoneStereoOn"
  allzonestereo_off:
    sequence:
      - service: input_boolean.turn_off
        entity_id: input_boolean.allzonestereostate
      - service: remote.send_command
        entity_id: remote.hub_salon
        data:
          device: "45999099"
          command: "AllZoneStereoOff"
  mutedenonsalon_onoff:
    sequence:
      - service: remote.send_command
        entity_id: remote.hub_salon
        data:
          device: "45999099"
          command: "Mute"
  mcsdenonsalon_onoff:
    sequence:
      - service: remote.send_command
        entity_id: remote.hub_salon
        data:
          device: "45999099"
          command: "MultiChStereo"
  harmony_shield_tv_onoff:
   sequence:
      - service: remote.turn_on
        entity_id: remote.hub_salon
        data:
          activity: "SHIELD TV"
  harmony_vinyle_onoff:
   sequence:
      - service: remote.turn_on
        entity_id: remote.hub_salon
        data:
          activity: "Vinyle Salon"
  harmony_off:
   sequence:
      - service: remote.turn_off
        entity_id: remote.hub_salon
  harmony_pc_onoff:
   sequence:
      - service: remote.turn_on
        entity_id: remote.hub_salon
        data:
          activity: "PC"
  start_junglekodi:
    sequence:
    - service: media_player.select_source
      data:
        entity_id: media_player.jungleshield
        source: 'org.xbmc.kodi'
  stop_junglekodi:
    sequence:
    - service: media_player.select_source
      data:
        entity_id: media_player.jungleshield
        source: '!org.xbmc.kodi'