notify:
  - name: pushbullet_3t
    platform: pushbullet
    api_key: !secret pushbullet_api

automation:
  - alias: 'Alerte - Pushbullet - Gel à venir'
    initial_state: 'off'
    trigger:
      platform: numeric_state
      entity_id: sensor.yr_temperature
      below: '5'
    action:
      service: notify.pushbullet_3t
      data:
        title: 'Alerte GEL'
        message: 'Rentres les plantes, il va geler'
  - alias: 'Alerte - Pushbullet - I have been pwned contactjunglemanfr'
    initial_state: 'on'
    trigger:
      platform: numeric_state
      entity_id: sensor.breaches_contactjunglemanfr
      above: 0
    action:
      service: notify.pushbullet_3t
      data:
        title: 'Fuite de donnée détectée'
        message: 'contact@jungleman.fr'
  - alias: 'Alerte - Pushbullet - I have been pwned mikaelboulogmailcom'
    initial_state: 'on'
    trigger:
      platform: numeric_state
      entity_id: sensor.breaches_contactjunglemanfr
      above: 2
    action:
      service: notify.pushbullet_3t
      data:
        title: 'Fuite de donnée détectée'
        message: 'mikael.boulo@gmail.com'
  - alias: 'Alerte - Pushbullet - Glances JungleNAS down'
    initial_state: 'on'
    trigger:
      platform: state
      entity_id: sensor.glances_running
      from: '1'
      to: 'unavailable'
      # Mesuré 30 secondes après coupure du service glances
    action:
      service: notify.pushbullet_3t
      data:
        title: 'Monitoring'
        message: 'JungleNAS semble être éteint !'
  - alias: 'Alerte - Pushbullet - Glances JungleNAS back'
    initial_state: 'on'
    trigger:
      platform: state
      entity_id: sensor.glances_running
      from: 'unavailable'
      # Mesuré 15 secondes après retour du service glances
    action:
      service: notify.pushbullet_3t
      data:
        title: 'Monitoring'
        message: 'JungleNAS est de retour !'