- alias: 'Lumières - Salon - Allumer au couché du soleil'
  initial_state: 'off'
  trigger:
    platform: sun
    event: sunset
    offset: -00:45:00
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: device_tracker.jungle_owntrack3t
        state: 'home'
      - condition: state
        entity_id: device_tracker.jungle3t_wifi
        state: 'home'
  action:
    - service: light.turn_on
      entity_id: light.salon
      data:
        transition: 600
        brightness: 200
- alias: 'Lumières - Salon - ON si luminosité basse'
  initial_state: 'on'
  action:
    entity_id: light.salon
    service: homeassistant.turn_on
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: light.salon
        state: 'off'
      - condition: or
        conditions:
          - condition: state
            entity_id: device_tracker.jungle_owntrack3t
            state: 'home'
          - condition: state
            entity_id: device_tracker.jungle3t_wifi
            state: 'home'
  trigger:
  - platform: numeric_state
    below: '300'
    entity_id: sensor.lumsens_1
- alias: 'Lumières - Salon - OFF si luminosité haute'
  action:
    entity_id: light.salon
    service: homeassistant.turn_off
  condition:
      condition: or
      conditions:
        #Tracking OWNTRACK
        - condition: state
          entity_id: device_tracker.jungle_owntrack3t
          state: 'home'
        #Tracking DD-WRT
        - condition: state
          entity_id: device_tracker.jungle3t_wifi
          state: 'home'
  trigger:
  - platform: numeric_state
    above: '300'
    entity_id: sensor.lumsens_1
  initial_state: 'off'
- alias: 'Lumières - Salon - Allumer soir'
  trigger:
    platform: sun
    event: sunset
    offset: "-00:45:00"  
  condition:
    - condition: state
      entity_id: device_tracker.jungle3t_wifi
      state: 'home'
    - condition: state
      entity_id: light.salon
      state: 'off'
    - condition: state
      entity_id: sensor.chromecastplex
      state: 'None'
  action:
    - service: light.turn_on
      entity_id: light.salon
      data:
        transition: 600
        brightness: 200